### ISSUE TITLE
Request to Implement Command Argument Placeholders

### ISSUE THREAD

**Issue by Exteron01** [72-S/CommandBridge#7]
Hey, can you please add a way to define a target player as a command argument? For example, I have a command configured on my Paper server like this:
command: 'litebans:tempban %player% 1d'.

Sadly, in this case, when I run the command I created for it in my Paper console (like /tempbanvelocity player123), it gets forwarded, but it bans %player%, not the username I provided in the command.

It would be really cool if you could fix this. Thanks!

**Comment by 72-S** [comment]
The plugin already has the ability to achieve this. I haven’t documented it yet, but you can use the placeholder %args% instead of %player%. You can then pass the player name as an argument into the command to execute, and it should work as expected.
