### ISSUE TITLE
1.21.3/4 support?

### ISSUE THREAD

**Issue by BeagleMiner** [72-S/CommandBridge#9]
Please update to 1.21.3/4 if possible.

**Comment by 72-S** [comment]
I am currently working on a rewrite, which will likely be published this week. It will include support for versions 1.21.3, 1.21.4, as well as earlier and later versions.

**Comment by 72-S** [comment]
@BeagleMiner [here you go](https://modrinth.com/plugin/commandbridge/version/2.0.0)
